# Step 1: Use an official Python runtime as a parent image
FROM python:3.12-slim

# Step 2: Set the working directory in the container
WORKDIR /server

# Step 3: Copy the requirements file to the container
COPY requirements.txt .

# Step 4: Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Step 5: Copy the entire project code to the container
COPY . .

# Step 6: Expose the port FastAPI will run on (default: 8000)
EXPOSE 8000

# Step 7: Define the command to run the FastAPI app with uvicorn
CMD ["uvicorn", "prediction.main:app", "--host", "0.0.0.0", "--port", "8000"]
